package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import lombok.Data;

@Data
public class Invoice {

    @ApiModelProperty(value = "Invoice id - autogenerated by appliaction", required = true, example = "17885131-2cf7-442f-a43b-1b022c0d5a3d")
    private UUID id;
    @ApiModelProperty(value = "Invoice date", required = true, example = "2021-10-02")
    private LocalDate date;
    @ApiModelProperty(value = "Vendor data", required = true)
    private Company vendor;
    @ApiModelProperty(value = "Purchaser data", required = true)
    private Company purchaser;
    @ApiModelProperty(value = "List of product/services", required = true)
    private List<InvoiceEntry> entries;

    public Invoice(@JsonProperty("date") LocalDate date, @JsonProperty("vendor") Company vendor,
                   @JsonProperty("purchaser") Company purchaser,
                   @JsonProperty("entries") List<InvoiceEntry> entries) {
        this.id = UUID.randomUUID();
        this.date = date;
        this.vendor = vendor;
        this.purchaser = purchaser;
        this.entries = entries;
    }
}
